production:
  environment: production
  short_code: "4167417"
  consumer_key: "ZHZwhQESEzHunurv7BQ9v0VKNrZz4YqLgej5YdS2RY9EvEzA"
  consumer_secret:  "EGUn7tRV2ZPPf3O6FG2xa1aIsYqRXA64yjocVJaTEw35gTjpJ7MBLswuCIWeVNs2"
  api_key: <%= ENV["MPESA_API_KEY"]%>
  callback_url: "https://net.yurento.com/webhooks/mpesa"
  api_url: "https://api.safaricom.co.ke/mpesa/stkpush/v1/processrequest"
  api_query_url: "https://api.safaricom.co.ke/mpesa/stkpushquery/v1/query"
  authorization_url: "https://api.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials"


development:
  environment: development
  short_code: "174379"
  consumer_key: EfCATJwZ99dotP5qQ5TDrHLUVHgsj4RlEnglClkKDwTaG0Zi
  consumer_secret:  Rc134o7Urbvpav61gGmR8IGqc5DYi0J1KUOXRx3hYtpSbx7WFirSorT55jAEd7CF
  api_key: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
  callback_url: "https://net.yurento.com/webhooks/mpesa"
  api_url: "https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest"
  authorization_url: "https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials"

