production:
  environment: production
  short_code: "4133627"
  consumer_key: "EnqlCHUlJIe0e7taDLgJ1WeNFtaGaT0It280fOVQ6lXDMnFF"
  consumer_secret:  "gQnKbJlxXVngqe1WI139gKiH3lGOhkn3jYMxZAMbGPJSUd55pQQDEKpBhIHFWtxG"
  api_key: <%= ENV["MPESA_API_KEY"]%>
  callback_url: "https://yurento.com/webhooks/mpesa"
  api_url: "https://api.safaricom.co.ke/mpesa/stkpush/v1/processrequest"
  api_query_url: "https://api.safaricom.co.ke/mpesa/stkpushquery/v1/query"
  authorization_url: "https://api.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials"


development:
  environment: development
  short_code: "174379"
  consumer_key: EfCATJwZ99dotP5qQ5TDrHLUVHgsj4RlEnglClkKDwTaG0Zi
  consumer_secret:  Rc134o7Urbvpav61gGmR8IGqc5DYi0J1KUOXRx3hYtpSbx7WFirSorT55jAEd7CF
  api_key: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
  callback_url: "https://yurento.com/webhooks/mpesa"
  api_url: "https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest"
  authorization_url: "https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials"

